feat: add search command
oclif/plugin-search pull request #14
Opened 2022-07-28 16:37 UTC by mdonnalley

Adds `search` command which uses a custom inquirer prompt

Note that I decided to leave the custom prompt in this code base for now instead of putting it into a different library. My reasoning is that it will be easier to iterate on the custom prompt wile it lives here and we can easily pull it out into it's own library once we have other use cases for it

2022-07-29 17:37 UTC, RodEsp requested changes

2022-07-29 17:37 UTC, RodEsp commented on src/util/autocomplete.ts
> +      output += ' (' + (typeof choice.disabled === 'string' ? choice.disabled : 'Disabled') + ')'
Same
```suggestion
      output += ` (${typeof choice.disabled === 'string' ? choice.disabled : 'Disabled'})`
```

2022-07-29 17:37 UTC, RodEsp commented on src/util/autocomplete.ts
> +    let line = (isSelected ? '❯' + ' ' : '  ') + choice.name
Same
```suggestion
    let line = `${isSelected ? '❯' : ' '} ${choice.name}`
```

2022-07-29 17:37 UTC, RodEsp commented on src/util/autocomplete.ts
> +      output += '  ' + choice + '\n'
Same
```suggestion
      output += `  ${choice}\n`
```

2022-07-29 17:37 UTC, RodEsp commented on src/util/autocomplete.ts
> +    output += line + ' \n'
```suggestion
    output += `${line} \n`
```

2022-07-29 17:37 UTC, RodEsp commented on src/util/autocomplete.ts
> +      bottomContent += '\n' + chalk.red('>> ') + error
Same
```suggestion
      bottomContent += `\n${chalk.red('>>')} ${error}`
```

2022-07-29 17:37 UTC, RodEsp commented on src/util/autocomplete.ts
> +      bottomContent += '  ' + chalk.yellow(this.opt.emptyText || 'No results...')
Not a huge deal but string templates are a little nicer to read imo
```suggestion
      bottomContent += `  ${chalk.yellow(this.opt.emptyText ?? 'No results...')}`
```

2022-08-02 14:32 UTC, mdonnalley commented on src/util/autocomplete.ts
> +}
Yes, mostly superfluous. But I did it mostly to avoid using `// @ts-expect-error` every time I instantiate `Choices`

2022-08-02 14:39 UTC, mdonnalley commented on src/util/autocomplete.ts
> +    return Promise.resolve(this)
It has to be async because it's extending the `_run` method in the `Base` class, which is async

2022-08-02 17:30 UTC, RodEsp approved these changes

2022-08-02 17:57 UTC, RodEsp commented
## QA

✔️ Prompts work
✔️ Autocomplete works

❔ Scrolling to a command and hitting `[Enter]` doesn't select/run a command, instead asks you to type something. I suppose this is FAD but it's kind of confusing from a UX perspective.
![enterOnCommandDoesntRunIt](https://user-images.githubusercontent.com/1084688/182441742-26b98814-97bb-4d5f-b7c4-3a91b60a3de2.gif)

❔ Similarly, after typing in a search term and selecting the one you want, hitting `[Enter]` doesn't run it. Instead it asks you which command you meant which is a little annoying since you already selected the one you wanted.
![enterOnCommandDoesntRunIt2](https://user-images.githubusercontent.com/1084688/182441993-5aef1c2b-78a1-4178-9d1b-0ea5154fc919.gif)

❔ For some reason this doesn't seem to be finding certain commands but I'm not sure why or if it's even a problem with this plugin or with some other part of oclif.
![image](https://user-images.githubusercontent.com/1084688/182440122-71b6eb83-4857-4a23-ad19-dfbcfe0a9358.png)

❌ Help doesn't contain anything
![image](https://user-images.githubusercontent.com/1084688/182440409-978b9c8b-8dbd-4945-897e-ff3e79b86032.png)

2022-08-03 15:17 UTC, peternhale approved these changes

2022-08-04 13:47 UTC, RodEsp commented
## QA 2

✔️ Prompts work
✔️ Autocomplete works
✔️ Scrolling to a command and hitting `[Enter]` shows the help for the selected command.
✔️ Similarly, after typing in a search term and selecting the one you want, hitting `[Enter]` shows the help for the command.
✔️ All commands are found.
✔️ Help for the search command exists.

2022-08-04 13:47 UTC, merged